### PR TITLE
Rebranding update

### PR DESCRIPTION
**Pull request by cdye**
Changed all instances of BaseSpace to either BaseSpace Sequence Hub or
BaseSpace Hub; replaced text with logo image in header.

### CODE REVIEW

**Comment by amaynard** [comment]
What's the guidline to choose  between Hub and Sequence Hub?

**Comment by cdye** [comment]
We only use BaseSpace Sequence Hub [long name] or BaseSpace Hub [short name]. Marketing requires the first use to spell out the entire name, and then the short name can be used elsewhere. Sequence Hub is never used by itself.

**Comment by amaynard** [comment]
Cool. Much prefer BaseSpace Hub...

**Comment by amaynard** [comment]
Can you please recreate the PR against develop? Then we can preview...

**Comment by cdye** [comment]
Done to #170

**Pull request closed without merging**
