### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by amaynard**

### CODE REVIEW

**Comment by amaynard** [comment]
@stefaniehenke Can you please review this new note? I'm also fixing the broken image in release notes header.

**Comment by stefaniehenke** [comment]
@almaynard Review/edit is done.

**Comment by amaynard** [comment]
Do we really want to name WalkMe? I don't think anybody knows that term.

**Comment by amaynard** [comment]
Thanks!

**Comment by stefaniehenke** [comment]
It's commonly used in VI, but in their implementation it's labeled as a WalkMe. Since it looks like we're not including it here, I agree it should be removed from the note.

**Pull request merged**
