### PR TITLE
Basemount v0.12 release

### PR DESCRIPTION
**Pull request by janinl**

### CODE REVIEW

**Comment by amaynard** [comment]
Haven't we tested 0.12?
> We have tested BaseMount Alpha v0.11.0 on the following systems:

**Comment by janinl** [comment]
> Newline starts with comma

Hmm... I hesitated... it's not a new line, it's the same sentence continuing with the code block in the middle...
I agree it looked weird.

**Comment by amaynard** [comment]
Best just start a new sentence "Where".

Do we know what the expiration is on our URLs?
> (7 days?)

**Comment by janinl** [comment]
> (7 days?)
yes, I just checked, and it's 7 days

**Comment by amaynard** [comment]
Getting picky now but I don't think this is right:
> CacheSizeLimit = 3e+11

**Pull request merged**
