### PR TITLE
Create 6.4.0.md

### PR DESCRIPTION
**Pull request by VahidVH**

### CODE REVIEW

**Review by whedley — APPROVED** [review]
TLTQ.

@gmoyerbrailean  Do we want to add a release note for the GDS dataset creation speed-up? Something like "Performance improvements to BCL Convert integration for NextSeq1000 runs" ?

**Review by gmoyerbrailean — CHANGES_REQUESTED** [review]
@whedley good point! Let's go with
- Performance improvements to BCL Convert integration for NextSeq 1000 & NextSeq 2000 systems

@VahidVH if you could include that, and also don't forget to add the 6.4.0.md file into index.html :) (eg #401)

**Comment by VahidVH** [comment]
@gmoyerbrailean @whedley added the RN for BCL convert performance improvement, and added the index.html changes too.

**Comment by VahidVH** [comment]
> @whedley good point! Let's go with
> 
> * Performance improvements to BCL Convert integration for NextSeq 1000 & NextSeq 2000 systems
> 
> @VahidVH if you could include that, and also don't forget to add the 6.4.0.md file into index.html :) (eg #401)

@gmoyerbrailean @whedley added the RN for BCL convert performance improvement, and added the index.html changes too.

**Comment by VahidVH** [comment]
@gmoyerbrailean @whedley added the RN for BCL convert performance improvement, and added the index.html changes too.

**Review by whedley — APPROVED** [review]
Nice. Good catch Greg, forgot about index.html.

**Pull request merged**
