### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by cdye**
Re-branded pages for Sequence Hub

### CODE REVIEW

**Comment by amaynard** [comment]
Is it OK to change the old release notes?

**Comment by cdye** [comment]
I expect because it's not changing anything beyond a name it should be OK.

**Comment by amaynard** [comment]
Merged in. Results here:
https://help.cloud-hoth.illumina.com

**Comment by cdye** [comment]
Thanks Al

Do we need to do something else to get it pushed live?

Christopher

**Comment by amaynard** [comment]
I just have to merge it in to master. Do we want to go live with it now or wait until 4.4 release?

**Comment by cdye** [comment]
Yeah go ahead and merge to master now. Thanks

**Comment by aroberts-illumina** [comment]
Was it tested in different browsers?

**Comment by amaynard** [comment]
Not by me... I think the only UI change was a new banner. Unfortunately it seems it is stuck refreshing in 
the CDN.

**Comment by cdye** [comment]
@aroberts-illumina 99% text changes, with the one change to the header area. Didn't test in multiple browsers as thought it was a minor change.

**Pull request merged**
